### ISSUE TITLE
How to escape commands/characters?

### ISSUE THREAD

**Issue by joshuacrotts** [Zeta611/simple-bnf#6]
I'm trying to add simple commands to the RHS of a rule, but no matter what method of escaping I try, nothing seems to work. Below is an example of me trying to add a single `\textquotesingle` to my rule which does not work. 

```LaTeX
        \begin{bnfgrammar}[lllll]
            datum ::= number
                  | boolean
                  | symbol
                  | character
                  | string;
            ;;
            string ::= \textquotesingle;
        \end{bnfgrammar}
```

**Comment by Zeta611** [comment]
You have redundant semicolons:
```TeX
\begin{bnfgrammar}[lllll]
  datum ::=
    number
  | boolean
  | symbol
  | character
  | string
;;
  string ::= \textquotesingle
\end{bnfgrammar}
```

**Comment by joshuacrotts** [comment]
Interesting. Trying this in Overleaf with the PDFLaTeX compiler causes a TeX stack size overflow(?). If I switch the compiler to XeLaTeX, it seems to work. Though, I'm curious as to why it doesn't work in Overleaf with this compiler. Funnily enough, when I use TeXStudio with PDFLaTeX, it generates a PDF, but it does not account for the alignment formatting.

Here's a link to the Overleaf example: https://www.overleaf.com/read/jrjwhvxkfxhb

Below is an image of TeXStudio's PDF output.

<img width="190" alt="Screen Shot 2022-11-30 at 9 08 19 PM" src="https://user-images.githubusercontent.com/18061804/204948819-1b3c1bb7-f168-4ec3-a9d4-2d465ccc9796.png">

**Comment by Zeta611** [comment]
TeXStudio is not working probably because it is using an old version of simplebnf, which did not have the alignment option. You can check by
```TeX
\usepackage{simplebnf}[2022/05/08]
```

I'll have to check with pdfLaTeX though.

**Comment by joshuacrotts** [comment]
I tried adding the date to the package, but that didn't fix it.

**Comment by Zeta611** [comment]
It does not fix the issue, but it should give you a log if you are using an older version. Can you please check it if it is the case?
Thank you!

**Comment by joshuacrotts** [comment]
Sure. It seems that it doesn't know that the newest version of the package doesn't exist. I wonder if it's because my packages might be out of date...

"You have requested, on input line 4, version `2022/05/08' of package simplebnf, but only version `2020/09/01 v0.2.0 A simple package to format Backus–Naur form' is available."

**Comment by Zeta611** [comment]
Yes, then that explains why TeXStudio is simply spitting out `[lllll]`. You need the updated version of the `.sty` file. 
You can either use `tlmgr` to update the package, or simply download the file from this repo and put in the same project directory. :)
