### ISSUE TITLE
RHS annotations are broken for `\in` productions

### ISSUE THREAD

**Issue by esclear** [Zeta611/simple-bnf#7]
Hi, thank you for this package, I like it very much.

I found that I can't add annotations to productions that use an `\in` as the delimiter:

The code
```latex
\begin{bnfgrammar}
    var \in X_s : variable of sort $s$
\end{bnfgrammar}
```
results in the following:
![grafik](https://user-images.githubusercontent.com/7432848/215301135-931f005d-e3c4-4116-b16c-01d33ee06ab9.png)

I tried to figure this out myself, but I'm not familiar enough with `xparse`, unfortunately.

Annotations work for the LHS, but not on the RHS.
How could I set annotations to the right of "`\in`-productions"?

**Comment by Zeta611** [comment]
Thank you for reporting the bug!

Indeed, the `\in` productions did not consider right annotations.
[61042c5](https://github.com/Zeta611/simplebnf/commit/61042c50bc27c484fbb86163ff2127d9b38ea98b) fixes this, and I'll publish it to CTAN soon.

In the meantime, you can use it immediately by putting the `.sty` file in the same directory.

Does it work for you?

**Comment by esclear** [comment]
Thanks a lot!
I can confirm that it works now, though I stumbled upon the fact that the RHS of `\in` productions is not rendered in a mathematics context anymore.
(Which, in my opinion is a good thing, because it's now consistent between the `::=` and `\in` productions.)
